# Generated by Django 2.2 on 2019-05-12 17:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190508_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created'], 'verbose_name': ('Товар',), 'verbose_name_plural': ('Товары',)},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': ('Категория товара',), 'verbose_name_plural': ('Категории товаров',)},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-created'], 'verbose_name': ('Картинка',), 'verbose_name_plural': ('Картинки',)},
        ),
        migrations.AlterField(
            model_name='product',
            name='text',
            field=tinymce.models.HTMLField(default='', max_length=200, verbose_name='Описание'),
        ),
    ]
